name: tkeskin
title: tkeskin
description: Yeşil baş ördek olsam su içmem gölünüzden
logo: assets/images/logo.png
favicon: assets/images/logo.png
github_username: tkeskin
url: 'http://tkeskin.github.io'
google_analytics: UA-51930769-28
disqus: tkeskin
include:
  - _pages
permalink: '/:title/'
authors:
  tkeskin:
    name: tkeskin
    display_name: tkeskin
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: tkeskin@gmail.com
    description: ''
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-admin
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 5
paginate_path: '/page:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: enabled
adsense-data-ad-client: ca-pub-2367630010898474
adsense-data-ad-slot: '6619221651'
lazyimages: enabled
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
